id: developer
name: Developer Onboarding
audience: "Developer"
summary: >
  Sets up a dev resource group and a starter repo in {{region}}.

vars:
  github_org: "navy-dev"
  repo_template: "starter-node-api"

tasks:
  - id: rg
    kind: tool
    title: "Create dev RG for {{user.alias}}"
    tool:
      name: "azure.create_resource_group"
      args:
        name: "rg-{{user.alias}}-dev"
        location: "{{region}}"
        tags:
          owner: "{{user.upn}}"
          env: "dev"

  - id: repo
    kind: tool
    title: "Create starter repo"
    tool:
      name: "github.create_repo_from_template"
      args:
        templateOwner: "{{vars.github_org}}"
        templateRepo: "{{vars.repo_template}}"
        owner: "{{vars.github_org}}"
        newRepoName: "{{user.alias}}-api"
        description: "Starter API for {{user.alias}}"
        visibility: "private"