id: mission-owner
name: Mission Owner – Day 0/1
audience: mission-owner
summary: >
  Creates a sandbox resource group, deploys an App Service skeleton,
  provisions a GitHub repo from a template with protections, and sets tags.

tasks:
  - id: rg
    kind: tool
    title: "Create sandbox RG rg-{{user.alias}}-sbx in {{region}}"
    tool:
      name: "azure.create_resource_group"
      args:
        name: "rg-{{user.alias}}-sbx"
        location: "{{region}}"
        tags:
          owner: "{{user.upn}}"
          env: "dev"

  - id: plan
    kind: tool
    title: "Create App Service Plan plan-{{user.alias}}-sbx (P1v3) in {{region}}"
    tool:
      name: "azure.create_app_service_plan"
      args:
        resourceGroupName: "rg-{{user.alias}}-sbx"
        name: "plan-{{user.alias}}-sbx"
        location: "{{region}}"
        skuName: "P1v3"

  - id: web
    kind: tool
    title: "Create Web App web-{{user.alias}} (NODE|20-lts)"
    tool:
      name: "azure.create_web_app"
      args:
        resourceGroupName: "rg-{{user.alias}}-sbx"
        name: "web-{{user.alias}}"
        planName: "plan-{{user.alias}}-sbx"
        location: "{{region}}"
        runtimeStack: "NODE|20-lts"

  - id: repo
    kind: tool
    title: "Provision GitHub repo {{user.alias}}-hello-web from template"
    tool:
      name: "github.create_repo_from_template"
      args:
        owner: "your-org"
        templateOwner: "your-org"
        templateRepo: "webapp-template"
        name: "{{user.alias}}-hello-web"
        private: true
        description: "Mission app for {{user.alias}}"

  - id: settings
    kind: tool
    title: "Apply app settings to web-{{user.alias}}"
    tool:
      name: "azure.web_set_app_settings"
      args:
        resourceGroupName: "rg-{{user.alias}}-sbx"
        name: "web-{{user.alias}}"
        settings:
          ENV: "dev"
          OWNER: "{{user.upn}}"

  - id: info-closeout
    kind: info
    title: "Review next steps in Teams channel"
    description: "Follow the checklist posted to the team channel and open a PR in the new repo."