id: aks-dev-cluster
name: AKS Dev Cluster
version: "1.0"

inputs:
  rgName: { required: true }
  region: { default: "usgovvirginia" }
  clusterName: { required: true }
  nodeCount: { default: 2 }
  nodeSize: { default: "Standard_D4s_v5" }
  privateCluster: { default: false }
  lawName: { required: false }        # Optional: if provided, create LAW and link

summary: |
  Creates an AKS cluster optimized for development workloads. Optionally provisions a Log Analytics workspace.

tasks:

  # Optional LAW first (if provided)
  - id: law
    title: Create Log Analytics Workspace (optional)
    kind: tool
    when: "{{lawName}}"
    tool:
      name: azure.create_log_analytics_workspace
      args:
        resourceGroupName: "{{rgName}}"
        name: "{{lawName}}"
        location: "{{region}}"
        sku: "PerGB2018"

  - id: aks
    title: Create AKS Cluster
    kind: tool
    tool:
      name: azure.create_aks_cluster    # ensure this tool exists in your Azure MCP
      args:
        resourceGroupName: "{{rgName}}"
        name: "{{clusterName}}"
        location: "{{region}}"
        kubernetesVersion: ""           # optional: let Azure pick default
        agentPoolProfiles:
          - name: "nodepool1"
            count: "{{nodeCount}}"
            vmSize: "{{nodeSize}}"
            mode: "System"
        apiServerAccessProfile:
          enablePrivateCluster: "{{privateCluster}}"

  # If you have a helper to enable monitoring (Container Insights), add it here
  - id: aks-monitor
    title: Enable AKS Monitoring (optional)
    kind: tool
    when: "{{lawName}}"
    tool:
      name: azure.enable_aks_monitoring   # add this helper to Azure MCP if not present
      args:
        resourceGroupName: "{{rgName}}"
        clusterName: "{{clusterName}}"
        workspaceResourceGroup: "{{rgName}}"
        workspaceName: "{{lawName}}"