id: basic-network
name: Basic Network (VNet + Subnets)
version: "1.0"

inputs:
  rgName: { required: true }
  region: { default: "usgovvirginia" }
  vnetName: { required: true }
  addressSpace: { default: "10.10.0.0/16" }
  subnets:
    default:
      - { name: "app",  cidr: "10.10.1.0/24" }
      - { name: "data", cidr: "10.10.2.0/24" }

summary: |
  Creates a virtual network and a set of subnets suitable for dev/test scenarios.

tasks:

  - id: vnet
    title: Create Virtual Network
    kind: tool
    tool:
      name: azure.create_virtual_network
      args:
        resourceGroupName: "{{rgName}}"
        name: "{{vnetName}}"
        location: "{{region}}"
        addressPrefixes: ["{{addressSpace}}"]

  # --- Loop over subnets (if your Onboarding MCP supports foreach)
  - id: subnets
    title: Create Subnets
    kind: tool
    foreach: "{{subnets}}"
    tool:
      name: azure.create_subnet
      args:
        resourceGroupName: "{{rgName}}"
        virtualNetworkName: "{{vnetName}}"
        name: "{{item.name}}"
        addressPrefix: "{{item.cidr}}"

  # If your engine does not support foreach, expand explicitly, e.g.:
  # - id: subnet-app
  #   kind: tool
  #   tool:
  #     name: azure.create_subnet
  #     args:
  #       resourceGroupName: "{{rgName}}"
  #       virtualNetworkName: "{{vnetName}}"
  #       name: "app"
  #       addressPrefix: "10.10.1.0/24"