id: mission-owner
name: Mission Owner – Day 0/1
audience: mission-owner
summary: >
  You are about to run the onboarding agent. This agent helps you create a sandbox resource group, deploys baseline infra from a curated Bicep template,
  provisions a mission GitHub repo from a template with protections, sets up your Teams channel,
  and points you to a couple of manual follow-ups.

tasks:
  - id: welcome
    kind: info
    title: "Welcome {{user.displayName}} — let’s set up your mission workspace."

  - id: baseline-rg
    kind: tool
    title: "Create baseline RG"
    description: "Create rg-{{user.alias}}-sandbox in usgovvirginia (tagged)."
    tool:
      name: "azure.create_resource_group"
      args:
        name: "rg-{{user.alias}}-sandbox"
        location: "usgovvirginia"
        tags:
          owner: "{{user.upn}}"
          env: "dev"
          costCenter: "0000"

  - id: deploy-baseline
    kind: tool
    title: "Deploy baseline infra (Bicep URL)"
    description: "Deploy networking/monitoring from a curated template."
    tool:
      name: "azure.deploy_bicep_rg_from_url"
      args:
        resourceGroupName: "rg-{{user.alias}}-sandbox"
        deploymentName: "baseline-{{user.alias}}"
        templateUrl: "https://raw.githubusercontent.com/PEDemoOrg/platform-configs/refs/heads/main/infra/baseline/biceo/onboard.bicep"
        parameters:
          namePrefix: "rg-{{user.alias}}-sandbox"
          environment: "dev"
          tags:
            owner: "{{user.upn}}"
            env: "dev"
            costCenter: "0000"

  - id: mission-repo
    kind: tool
    title: "Create mission repo (with Q&A)"
    description: "We’ll ask a couple questions (template, name, privacy) and then create the repo."
    tool:
      name: "github.repo_wizard_mission_owner"
      args:
        org: "PEDemoOrg"         # default org; wizard can override
        defaultVisibility: "private"
        suggestName: "mission-{{user.alias}}-infra"
        teamSlug: "developers"           # optional team to grant push access

  - id: teams-channel
    kind: tool
    title: "Create Teams channel"
    description: "Creates #mission-{{user.alias}} in your governance team."
    tool:
      name: "teams.create_channel"
      args:
        teamId: "<governance-team-id>"
        displayName: "mission-{{user.alias}}"
        description: "Mission comms"

  - id: join-announce
    kind: manual
    title: "Join #eng-announcements and #platform"
    description: "Ask your buddy to add you if needed."
